let () =
  Alcotest.run "fret_not"
    [ ("pitch_class", Pitch_class_test.tests)
    ; ("alteration", Alteration_test.tests)
    ; ("letter", Letter_test.tests)
    ; ("spelled_pitch", Spelled_pitch_test.tests)
    ; ("note", Note_test.tests)
    ; ("scale_degree", Scale_degree_test.tests)
    ; ("mode", Mode_test.tests)
    ; ("scales", Scales_test.tests)
    ; ("key", Key_test.tests)
    ; ("degree_reference", Degree_reference_test.tests)
    ; ("tuning", Tuning_test.tests)
    ; ("instrument", Instrument_test.tests)
    ; ("reach", Reach_test.tests)
    ; ("shape", Shape_test.tests)
    ; ("fretboard", Fretboard_test.tests)
    ; ("fretboard_layout", Fretboard_layout_test.tests)
    ; ("tab_layout", Tab_layout_test.tests)
    ; ("row_layout", Row_layout_test.tests)
    ; ("page_layout", Page_layout_test.tests)
    ; ("chunk_layout", Chunk_layout_test.tests)
    ; ("fretboard_view_state", Fretboard_view_state_test.tests)
    ; ("chunk_view_state", Chunk_view_state_test.tests)
    ; ("chunk", Chunk_test.tests)
    ; ("chunk_solver", Chunk_solver_test.tests)
    ]
;;
